- name: update everything, except for filesystem
  dnf:
    name: '*'
    state: latest
    update_cache: true
    exclude: filesystem*
  when: ansible_distribution == 'CentOS'

- name: update everything (alpine)
  apk:
    upgrade: true
  when: ansible_distribution == 'Alpine'
