---
- name: add nginx-mainline repo
  yum_repository:
    name: nginx-mainline
    description: nginx mainline repo
    baseurl: http://nginx.org/packages/mainline/centos/$releasever/$basearch/
    gpgcheck: yes
    enabled: yes
    gpgkey: https://nginx.org/keys/nginx_signing.key

- name: install nginx
  package:
    name: nginx
    state: latest

- name: set nginx.conf in /etc/nginx/
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: enable nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
