---
- name: Master Playbook
  hosts: all
  become: yes
  roles:
    # - baseline
    # - bitwarden
    # - caddy
    # - docker
    # - duo
    # - letsencrypt
    # - plex
    # - step_ca
  handlers:
    - import_tasks: roles/caddy/handlers/main.yml
    - import_tasks: roles/firewalld/handlers/main.yml
