---
- name: get copr repo
  dnf:
    name: "dnf-command(copr)"
    state: present

- name: check to see if repo exists
  stat:
    path: "/etc/yum.repos.d/_copr:copr.fedorainfracloud.org:group_caddy:caddy.repo"
  register: caddyrepo

# dnf copr -y enable @caddy/caddy
# abstraction barriers!
- name: enable copr repo
  command: dnf copr -y enable @caddy/caddy
  when: not caddyrepo.stat.exists

- name: install caddy
  dnf:
    name:
      - caddy
      - nss-tools
    state: latest

- name: check to see if Caddyfile exists
  stat:
    path: /etc/caddy/Caddyfile
  register: caddyfile_exists

- name: create Caddyfile
  file:
    path: /etc/caddy/Caddyfile
    state: touch
  when: not caddyfile_exists.stat.exists

- name: enable http/s in firewalld
  import_tasks: roles/firewalld/handlers/main.yml
  vars:
    firewalld_services:
      - http
      - https

- name: enable caddy service
  service:
    name: caddy
    state: started
    enabled: true
