---
- name: get copr repo
  dnf:
    name: "dnf-command(copr)"
    state: present

- name: check to see if repo exists
  stat:
    path: "/etc/yum.repos.d/_copr:copr.fedorainfracloud.org:group_caddy:caddy.repo"
  register: caddyrepo

# dnf copr -y enable @caddy/caddy
# abstraction barriers!
- name: enable copr repo
  command: dnf copr -y enable @caddy/caddy
  when: not caddyrepo.stat.exists

- name: install caddy and deps
  dnf:
    name:
      - caddy
      - nss-tools
    state: latest

- name: setup caddy config
  blockinfile:
    path: /etc/caddy/Caddyfile
    marker: "# {mark} ANSIBLE MANAGED config"
    block: |
      {
        experimental_http3
        email {{ email }}
      }
    create: yes
    insertbefore: BOF
    validate: caddy adapt --config %s --validate

- name: enable http/s in firewalld
  import_tasks: roles/firewalld/handlers/main.yml
  vars:
    firewalld_services:
      - http
      - https

- name: enable caddy service
  service:
    name: caddy
    state: started
    enabled: true
